### PR TITLE
Added Payment Methods Implementation + Fixed Search Feature + Fixed feedPage-test.tsx Testing

### LINKED ISSUE #76: Add Selectable Payment Methods to Display on Contact Cards
Users should be able to easily see which payment methods are valid for cost-splitting on rides. User should be able to input their own available payment methods, and be able to see others when viewing RSVPed rides.

### LINKED ISSUE #78: Search feature broken
Typing in the search bar does not automatically update the corresponding posts in the feed.

### LINKED ISSUE #82: feedPage Unit Tests Failing
feedPage-test.tsx unexpectedly results in low coverage and numerous failing tests. May have been caused by changes in functionality on feedPage.tsx and may require updating.

### PR DESCRIPTION
**Pull request by KevinS0402**
**1. Added payment method implementation:**

- Users can now select payment methods that they have in order to facilitate easy cost-splitting for ridesharing on the **Edit Profile** page. The payment method input shows up at the bottom, with clickable buttons to select each payment method. (see below) 

IMG_7025

- Users' payment methods will be displayed in their own individual contact cards on rides that they have RSVPed for. (see below) 

IMG_7024

**2. Fixed search feature that was broken in previous versions (users can now search in any combo or order of creator name, destination, and time/date)**
IMG_7027
IMG_7029

**3. Fixed feedPage-test.tsx Unit Testing** (Achieved 100% coverage and 100% of tests passing)
* Note: Sometimes the individual test (e.g., running `` bun test ./__tests__/feedPage-test.tsx``) can result in a Segmentation fault due to Bun testing still being experimental. You can instead run ``npx jest __tests__/feedPage-test.tsx`` to see the individual test results, or just ``bun run test`` to see results for all test suites (the feedPage-test.tsx will work as well).
image
image

Closes #76 
Closes #78 
Closes #82 

(FYI the screenshots were taken in iOS Expo Go instead of the usual Android simulator, but still works in the Expo Android simulator)

### CODE REVIEW

File: app/rsvp.tsx [hunk 1]
```diff
@@ -38,11 +38,16 @@ export type RideDataType = {
   returns: Timestamp;
 };
 
+export type RideWithCreatorName = RideDataType & {
+  creatorName: string;
+};
+
```
Comment (kohrachel) [inline app/rsvp.tsx]: Since there's a finite number of accepted payment methods we should explicitly state what they are to avoid capitalization/spelling/hyphenation issues

```suggestion
  const AllowedPaymentMethods = "PayPal" | "Apple Cash" | "Venmo" | "Zelle" | "Google Pay" | "Cash App"
  type PaymentMethodsType = AllowedPaymentMethods[]
```

File: components/contactCard.tsx [hunk 2]
```diff
@@ -13,6 +13,7 @@ type ContactCardProps = {
   phoneNum: string;
   email: string;
   gender: UserGenderType;
+  paymentMethods: string[];
```
Comment (kohrachel) [inline components/contactCard.tsx]: See previous comments about typing in `rsvp.tsx`

File: app/editProfile.tsx [hunk 3]
```diff
@@ -297,4 +346,42 @@ const styles = StyleSheet.create({
...
+  paymentOption: {
+    paddingVertical: 4,
+    paddingHorizontal: 10,
+    borderRadius: 16,
+    borderWidth: 1,
+    borderColor: "#555",
+    backgroundColor: "transparent",
+  },
+  paymentOptionSelected: {
+    backgroundColor: "#4CAF50",
```
Comment (kohrachel) [inline app/editProfile.tsx]: please match the color scheme in canva (I don't see this hex code in our design)

File: components/contactCard.tsx (hunk 2 above)
Comment (KevinS0402) [reply components/contactCard.tsx]: Updated in newest code
