### PR TITLE
Fix Ride Post UI + Contact Card Schema 

### LINKED ISSUE #23: RSVP button needs to enable editing RSVP status

### LINKED ISSUE #24: RSVP button disabled when ride is full

### PR DESCRIPTION
**Pull request by kohrachel**
## Updated Contact Card 

Changes: 

- Phone number is formatted as `(XXX) XXX-XXXX`
- Gender added to the component
- (sync with db) deprecated `firstName` and `lastName`, replaced with `name`

Visually: 

image

## Updated Ride Post UI 

Header shows the destination rather than the name of the user who created the ride 

image

### Gender based RSVP for safety

Rides can optionally specify a gender restriction (e.g. female only rides). Only logged in users who have their gender saved as `Female` in their profile can RSVP to a female only ride, and vice versa for `Male` and male only rides.

image

### RSVP disabled when gender of user (Female) doesn't match ride restriction
image

### RSVP disabled when ride is full 
image

Closes #24 
Closes #23

### CODE REVIEW

File: components/SingleRidePost.tsx [hunk 1]
```diff
@@ -94,16 +119,20 @@ export default function SingleRidePost({ rideId }: SingleRidePostProps) {
     );
   }
 
+  const isRsvpDisabled = () => {
+    if (rideData?.currPpl >= (rideData?.maxPpl || 0) && !isUserRsvped)
+      return true;
+    if (rideData?.gender !== "Co-ed" && rideData?.gender !== userData?.gender)
```
Comment (23reide) [inline components/SingleRidePost.tsx]: Thank you for implementing that
